```{r}
library(tidyverse)
library(simtrait)
library(gdata)
```

# load data
```{r}
traits=("LOG_tg")


traits <- c("height", "LOG_a2h_ins", "LOG_creatinine", "LOG_adiponectin", 
            "LOG_leptin", "LOG_chol", "LOG_ldl", "LOG_hdl", "LOG_tg", "LOG_bmi", "LOG_hipc", 
            "LOG_waistc", "LOG_whr", "LOG_dbp", "LOG_cystatin_c", "t2d", 
            "LOG_fast_glu", "LOG_sbp", "LOG_fast_ins", "LOG_a2h_glu", "LOG_weight")


# Iterate over each trait
for (trait in traits) {
  
  # Construct the file paths dynamically based on the trait
  joint_file <- paste0("./saige/saige_output_", trait, "_trait_age.txt")
  meta_file <- paste0("/hpc/dctrl/tt207/meta_analysis_aim/METAL/samafs/output_metal_sex_", trait, "_trait_age1.txt")
  
  # Read in the data
  joint <- read.table(joint_file, header = TRUE)
  meta <- read.table(meta_file, header = TRUE)
  
  # Calculate p-value inflation
  pval_trait <- c(pval_infl(joint$p.value), pval_infl(meta$P.value))
  
  # Assign pval_trait to a new variable named after the current trait
  assign(trait, pval_trait)
  
  # Optional: Print or further process the results
  print(paste("Processed trait:", trait))
  print(get(trait))
}

df = rbind(height, LOG_a2h_ins, LOG_creatinine, LOG_adiponectin, 
            LOG_leptin, LOG_chol, LOG_ldl, LOG_hdl, LOG_tg, LOG_bmi, LOG_hipc, 
            LOG_waistc, LOG_whr, LOG_dbp, LOG_cystatin_c, t2d, 
            LOG_fast_glu, LOG_sbp, LOG_fast_ins, LOG_a2h_glu, LOG_weight) %>% as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(trait = rowname, joint_lambda = V1, meta_lambda = V2)

write.table(df, "/hpc/dctrl/tt207/meta_analysis_aim/samafs/inflation_factor_data.txt", col.names = TRUE, row.names = FALSE)

```

```{r fig.width=6, fig.height=4}
library(ggplot2)
ggplot(df, aes(x = joint_lambda, y = meta_lambda)) +
  geom_point() +
  theme_bw() +
  geom_segment(aes(x = min(df$meta_lambda), y = min(df$meta_lambda), 
                   xend = max(df$meta_lambda), yend = max(df$meta_lambda),
                   linetype = "y = x", color = "y = x"), size = 1) +  # y = x line
  geom_vline(aes(xintercept = 1.05, linetype = "x = 1.05", color = "x = 1.05"), size = 1) +  
  geom_hline(aes(yintercept = 1.05, linetype = "y = 1.05", color = "y = 1.05"), size = 1) +  
  coord_equal() +  
  scale_colour_manual(name = NULL, values = c("y = x" = "red", "x = 1.05" = "gray", "y = 1.05" = "gray")) + 
  scale_linetype_manual(name = NULL, values = c("y = x" = "dashed", "x = 1.05" = "solid", "y = 1.05" = "solid")) + 
  labs(colour = NULL, linetype = NULL, 
       x = "Joint analysis inflation factor", 
       y = "Sex-stratified meta-analysis inflation factor") +
  theme(legend.position = "top")

```


