```{r}
library(tidyverse)
library(simtrait)
library(gdata)
```

# load data
```{r}

traits <- c("height", "LOG_a2h_ins", "LOG_creatinine", "LOG_adiponectin",
            "LOG_leptin",  "LOG_ldl", "LOG_hdl", "LOG_tg", "LOG_chol", "LOG_bmi", "LOG_hipc",
            "LOG_waistc", "LOG_whr", "LOG_dbp", "LOG_cystatin_c", "t2d",
            "LOG_fast_glu", "LOG_sbp", "LOG_fast_ins", "LOG_a2h_glu", "LOG_weight")


# Iterate over each trait
for (trait in traits) {
  
  # Construct the file paths dynamically based on the trait
  joint_file <- paste0("./saige_loco/saige_output_", trait, "_loco.txt")
  meta_file <- paste0("./metal/output_metal_sex_", trait, "_loco1.txt")
  
  # Read in the data
  joint <- read.table(joint_file, header = TRUE)
  meta <- read.table(meta_file, header = TRUE)
  
  # Calculate p-value inflation
  pval_trait <- c(pval_infl(joint$p.value), pval_infl(meta$P.value))
  
  # Assign pval_trait to a new variable named after the current trait
  assign(trait, pval_trait)
  
  # Optional: Print or further process the results
  print(paste("Processed trait:", trait))
  print(get(trait))
}

# df = rbind(LOG_bmi, LOG_whr, LOG_waistc) %>% as.data.frame() %>% 
#   rownames_to_column() %>% 
#   rename(trait = rowname, joint_loco_lambda = V1, meta_loco_lambda = V2)

df = rbind(height, LOG_a2h_ins, LOG_creatinine, LOG_adiponectin,
            LOG_leptin, LOG_chol, LOG_ldl, LOG_hdl, LOG_tg, LOG_bmi, LOG_hipc,
            LOG_waistc, LOG_whr, LOG_dbp, LOG_cystatin_c, t2d,
            LOG_fast_glu, LOG_sbp, LOG_fast_ins, LOG_a2h_glu, LOG_weight) %>% as.data.frame() %>%
  rownames_to_column() %>%
  rename(trait = rowname, joint_loco_lambda = V1, meta_loco_lambda = V2)

write.table(df, "/home/tt207/pro00108518/t2d-samafs/study2/exome_chip/cryptic-relatedness/inflation_factor_loco.txt", col.names = TRUE, row.names = FALSE)

```

```{r}
no_loco = read.table("inflation_factor_data.txt", header = TRUE)
combine_lambda = merge(no_loco, df, by  = "trait") %>% 
  pivot_longer(
    cols = -trait,
    names_to = c("method", "LOCO"),
    names_pattern = "(joint|meta)_(loco)?_?lambda",
    values_to = "lambda"
  ) %>%
  mutate(
    LOCO = ifelse(LOCO == "loco", TRUE, FALSE)
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = lambda,
    names_glue = "{method}_lambda"
  )
  
```

```{r fig.width=4, fig.height=3}
library(ggplot2)


ggplot(combine_lambda, aes(x = joint_lambda, y = meta_lambda)) +
  # LOCO points with first color scale
  geom_point(aes(color = LOCO)) +
  #scale_color_manual(values = c("FALSE" = "black", "TRUE" = "blue"), name = "LOCO") +
  
  # reset for a second independent color scale
  ggnewscale::new_scale_color() +
  
  # reference lines with their own color/linetype mapping
  geom_abline(aes(intercept = 0, slope = 1, 
                  linetype = "y = x", color = "y = x"), size = 1) +
  geom_vline(aes(xintercept = 1.05, 
                 linetype = "x = 1.05", color = "x = 1.05"), size = 1) +
  geom_hline(aes(yintercept = 1.05, 
                 linetype = "y = 1.05", color = "y = 1.05"), size = 1) +
  
  scale_color_manual(values = c("y = x" = "navy", "x = 1.05" = "gray", "y = 1.05" = "gray"), 
                     name = NULL) +
  scale_linetype_manual(values = c("y = x" = "dashed", "x = 1.05" = "solid", "y = 1.05" = "solid"),
                        name = NULL) +
  
  coord_equal() +
  labs(x = "Joint analysis inflation factor", 
       y = "Sex-stratified meta-analysis inflation factor") +
  theme_bw() +
  theme(legend.position = "top")
```

```{r}
combine_lambda = merge(no_loco, df, by = "trait") %>% 
  pivot_longer(
    cols = -trait,
    names_to = c("method", "LOCO"),
    names_pattern = "(joint|meta)(_loco)?_lambda",
    values_to = "lambda"
  ) %>%
  mutate(
    LOCO = ifelse(LOCO == "_loco", "loco", "no_loco")
  ) %>%
  pivot_wider(
    names_from = LOCO,
    values_from = lambda
  )

ggplot(combine_lambda, aes(x = no_loco, y = loco)) +
  # LOCO points with first color scale
  geom_point(aes(color = method)) + 
  ggnewscale::new_scale_color() +
  # reference lines with their own color/linetype mapping
  geom_abline(aes(intercept = 0, slope = 1, 
                  linetype = "y = x", color = "y = x"), size = 1) +
  scale_color_manual(values = c("y = x" = "navy"), 
                     name = NULL) +
  scale_linetype_manual(values = c("y = x" = "dashed", "x = 1.05" = "solid", "y = 1.05" = "solid"),
                        name = NULL) +
  coord_equal() +
  labs(x = "LOCO = FALSE", 
       y = "LOCO = TRUE") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(aspect.ratio = 1)
```

